language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - echo "deb https://dl.bintray.com/pcp/wheezy wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran libblas-dev liblapack-dev
  - sudo apt-get install -y --allow-unauthenticated libpcp3=3.11.7 libpcp3-dev=3.11.7 pcp-conf=3.11.7 libpcp-pmda3-dev=3.11.7 libpcp-pmda3=3.11.7 libpcp-gui2-dev=3.11.7 libpcp-gui2=3.11.7 libpcp-import1-dev=3.11.7 libpcp-import1=3.11.7 libpcp-mmv1=3.11.7 libpcp-trace2=3.11.7 libpcp-mmv1-dev=3.11.7 libpcp-trace2-dev=3.11.7
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - if [ $TRAVIS_PYTHON_VERSION != "2.6" ]; then pylint --errors-only --disable=F0401,E0611 supremm; fi
  - if [ $TRAVIS_PYTHON_VERSION != "2.6" ]; then pylint --errors-only --disable=E0611 supremm; fi
  - cd tests && python -m unittest discover
