language: python
python:
  - "2.7"
before_install:
  - echo "deb https://dl.bintray.com/pcp/wheezy {distribution} {components}" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcp3 libpcp3-dev
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: python -m unittest discover -s tests && pylint --errors-only supremm
